version: "3.8"

services:
  python_bot:
    build: .  # Собираем образ из Dockerfile
    ports:
      - "5000:5001"  # Пробрасываем порт 5001 на хост
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер (для разработки)
    environment: # Устанавливаем переменные окружения
      - BOT_TOKEN={TOKEN}
      - GOOGLE_CREDS_JSON_PATH=google_config.json
      - GOOGLE_SHEET_NAME={google_sheet_name}
      - HF_TOKEN={HF_TOKEN}